### PR TITLE
Add support for minted embedded

### PR DESCRIPTION
**Pull request by yitzchak**
Initial commit with languages that language-gfm supports and have obvious minted
version.

### CODE REVIEW

**Comment by yudai-nkt** [comment]
Thank you for this amazing feature! I want to merge this, but percent sign, which programming languages often use for modulo operation, acts as a TeX's comment character in some cases.

```
\begin{minted}{python}
    def main(start, stop):
        for i in range(start, stop):
            if (i % 15) == 0:
                print 'FizzBuzz'
            elif (i % 5) == 0:
                print 'Buzz'
            elif (i % 3) == 0:
                print 'Fizz'
            else:
                print i
\end{minted}
\begin{minted}{c}
    #include <stdio.h>
    int main(void) {
        int i;
        for (i = 1; i <= 100; i++) {
            if (i % 3 == 0 && i % 5 == 0) {
                printf("FizzBuzz\n");
            } else if (i % 3 == 0) {
                printf("Fizz\n");
            } else if (i % 5 == 0) {
                printf("Buzz\n");
            } else {
                printf("%d\n", i);
            }
        }
        return 0;
    }
\end{minted}
```

will give

**Comment by yudai-nkt** [comment]
I really love this PR, but on the other hand I wonder if this is really necessary for LaTeX a little bit. IMHO, the purpose of syntax highlight is to visually help users write codes, and what's written in `minted` environment is irrelevant to the _correctness_ of code in terms of (La)TeX.

For example, highlighting gnuplot syntax in `gnuplot` environment from [`gnuplottex`](https://www.ctan.org/pkg/gnuplottex) package is helpful because the gnuplot commands are executed when you typeset the LaTeX source. However, embedded codes of C, Java, or whatever, in `minted` environment are just printed on the output. They have no meaning as a programming language itself in this case. If one wants to embed grammatically right codes to LaTeX document, he/she should consider using `\inputminted` (this will also improve the maintainability of document).

This is just a subjective opinion, so I'd like to know yours if you have.

**Comment by yitzchak** [comment]
I do not think there is a way to fix the percent sign issue. The syntax highlighting in Atom appears to me to be additive and context free. In other words, I do not think it is possible to say do  **not** use LaTeX highlighting inside of a minted environment.

In regards to whether the PR is really needed or not, I can go either way. `language-gfm`, `language-markdown`, and `language-html` all appear to work this way, but you are right it is not really required to make `language-tex` syntax highlighting work.

**Comment by yudai-nkt** [comment]
`language-c` does not assign any meaning to percent sign for both modulo operator and format specifier while `language-python` assigns `keyword.operator.arithmetic.python` to it. I tried Java and C#, and they handled percent sign well in `minted` environement.

So this seems to be a problem of `language-c` package rather than the PR. I will look into the details later anyway.

**Comment by yudai-nkt** [comment]
cf. atom/language-c#123

**Pull request merged**
